# A sample Makefile for building Google Test and using it in user
# tests.  Please tweak it to suit your environment and project.  You
# may want to move it to your project's root directory.
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.
#
# Please tweak the following variable definitions as needed by your project


CC = g++
RM  = rm -f

# Configure Paths.
BOOST_INCLUDE = /cspshare/opt/lib/boost/include
BOOST_LIB = /cspshare/opt/lib/boost/lib
GTEST_DIR = /cspshare/src/gtest/gtest-1.7.0
GTEST_LIB = /cspshare/opt/lib/gtest/lib
GTEST_INCLUDE=/cspshare/opt/lib/gtest/include
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h $(GTEST_DIR)/include/gtest/internal/*.h
XML_REPORT = -gtest_output="xml:./test/Report.xml"
EXE = runner
SRC = $(wildcard src/*.cpp)
OBJ = $(SRC:.cpp=.o)
CFLAGS = -w -std=c++11 -g -Wall -Wextra -lpthread -pedantic
BFLAGS = -I $(BOOST_INCLUDE) -L $(BOOST_LIB) -DBOOST_LOG_DYN_LINK -O0 -lm -lboost_log -lboost_thread -lboost_system -lboost_filesystem -lboost_date_time -lboost_chrono -lboost_regex
GFLAGS = -isystem $(GTEST_INCLUDE)

# Flags passed to the preprocessor.
FLAGS = $(CFLAGS) $(BFLAGS)

all: $(EXE)

$(EXE): $(OBJ)
	$(CC) $(FLAGS) $(OBJ) -o $(EXE)

%.o: %.cpp
	$(CC) -c $(FLAGS) $< -o $@

clean:
	$(RM) $(EXE) *.log $(OBJ)
